version: "3"

volumes:
  data01:
    driver: local

services:
  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  backend:
    container_name: backend
    build:
      context: api
    volumes:
    - /tmp/logs/backend/:/var/log/backend/
    ports:
      - 8888:8888
    depends_on:
      - es01
      - redis
    environment:
      LOGSTASH_HOST=logstash

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    volumes:
    - /tmp/logs/nginx/:/var/log/nginx/
    environment:
      - API_HOST=http://backend
      - API_PORT=8888
    ports:
      - 0.0.0.0:80:80
    restart: on-failure

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - LOSTASH_HOST=localhost:5045
    depends_on:
      - backend
      - nginx
