version: "3"

volumes:
  data01:
    driver: local

services:
  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  backend:
    container_name: backend
    build:
      context: api
    ports:
      - 8888:8888
    depends_on:
      - es01
      - redis
    environment:
      LOGSTASH_HOST=logstash
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    environment:
      - API_HOST=http://backend
      - API_PORT=8888
    ports:
      - 0.0.0.0:80:80
    restart: on-failure
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:5044
        tag: nginx

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      discovery.type: single-node
    ports:
      - 9201:9200
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch