version: '3.3'
services:

  film-db:
    image: postgres:12.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - 8000:5432